'use strict';

module.exports = app => {
  const { router, controller, jwt } = app;
  router.get('/api/login/code', controller.login.code);
  router.post('/api/login', controller.login.login);
  router.get('/api/logout', jwt, controller.login.logout);
  router.get('/api/home/info', jwt, controller.home.info);
  router.get('/api/home/main', jwt, controller.home.main);
  router.get('/api/user', jwt, controller.user.index);
  router.get('/api/user/detail', jwt, controller.user.getUserDetail);
  router.post('/api/user/update', jwt, controller.user.updateDetail);
  router.get('/api/user/order', jwt, controller.user.getUserOrder);
  router.get('/api/user/address', jwt, controller.user.getUserAddress);
  router.get('/api/user/cart', jwt, controller.user.getUserCart);
  router.get('/api/user/foot', jwt, controller.user.getUserFoot);
  router.get('/api/user/allShopCartList', jwt, controller.user.getAllShopCartList);
  router.get('/api/order', jwt, controller.order.index);
  router.get('/api/order/detail', jwt, controller.order.getOrderDetail);
  router.post('/api/order/goDelivery', jwt, controller.order.goDelivery);
  router.get('/api/express/getAutomaticDeliveryStatus', jwt, controller.express.getAutomaticDeliveryStatus);
  router.get('/api/express/type', jwt, controller.express.type);
  router.get('/api/region/all', jwt, controller.region.getAll);
  router.get('/api/region/allArea', jwt, controller.region.getAllArea);
  router.post('/api/order/saveSellerMemo', jwt, controller.order.saveSellerMemo);
  router.get('/api/order/revisePrice', jwt, controller.order.revisePrice);
  router.get('/api/order/checkExpress', jwt, controller.order.checkExpress);
  router.get('/api/order/regenerateOrderSn', jwt, controller.order.regenerateOrderSn);
  router.get('/api/shop/expressSettings', jwt, controller.shop.expressSettings);
  router.post('/api/shop/setSettings', jwt, controller.shop.setSettings);
  router.get('/api/express/changeStatus', jwt, controller.express.changeStatus);
  router.get('/api/express/detail', jwt, controller.express.detail);
  router.post('/api/express/edit', jwt, controller.express.edit);
  router.get('/api/express/getFreightTemplate', jwt, controller.express.getFreightTemplate); // 获取运费模板列表
  router.get('/api/express/getFreightTemplateDetail', jwt, controller.express.getFreightTemplateDetail); // 获取指定运费模板详情
  router.delete('/api/express/deleteFreightTemplate', jwt, controller.express.deleteFreightTemplate);
  router.get('/api/express/canUseShipper', jwt, controller.express.canUseShipper);
  router.post('/api/express/saveFreightTemplate', jwt, controller.express.saveFreightTemplate);
  router.get('/api/goods/list', jwt, controller.goods.getGoodsList);
  router.get('/api/goods/simpleList', jwt, controller.goods.getGoodsSimpleList);
  router.delete('/api/goods/deleteGoods', jwt, controller.goods.deleteGoods);
  router.post('/api/goods/changeGoodsStatus', jwt, controller.goods.changeGoodsStatus);
  router.get('/api/goods/detail', jwt, controller.goods.getGoodsDetail);
  router.get('/api/category', jwt, controller.category.index);
  router.get('/api/goods/specification', jwt, controller.goods.getAllSpecification);
  router.post('/api/goods/save', jwt, controller.goods.save);
  router.post('/api/category/changeIconDisplay', jwt, controller.category.changeIconDisplay);
  router.post('/api/category/changeShowIndex', jwt, controller.category.changeShowIndex);
  router.post('/api/category/changeSortOrder', jwt, controller.category.changeSortOrder);
  router.delete('/api/category/delete', jwt, controller.category.deleteCategory);
  router.post('/api/goods/changeSpecificationName', jwt, controller.goods.changeSpecificationName);
  router.post('/api/goods/changeSpecificationSortOrder', jwt, controller.goods.changeSpecificationSortOrder);
  router.delete('/api/goods/deleteSpecification', jwt, controller.goods.deleteSpecification);
  router.get('/api/category/info', jwt, controller.category.info);
  router.post('/api/category/save', jwt, controller.category.save);
  router.post('/api/goods/saveSpecification', jwt, controller.goods.saveSpecification);
  router.get('/api/shop/advertisement', jwt, controller.shop.getAdvertisement);
  router.post('/api/shop/advertisement/changeState', jwt, controller.shop.changeAdvertisementState);
  router.delete('/api/shop/advertisement/delete', jwt, controller.shop.deleteAdvertisement);
  router.get('/api/shop/advertisement/detail', jwt, controller.shop.getAdvertisementDetail);
  router.post('/api/shop/advertisement/save', jwt, controller.shop.saveAdvertisement);
  router.get('/api/shop/showSet', jwt, controller.shop.getShowSetting);
  router.post('/api/shop/saveShowSet', jwt, controller.shop.saveShowSetting);
  router.get('/api/shop/getNotice', jwt, controller.shop.getNotice);
  router.post('/api/shop/saveNotice', jwt, controller.shop.saveNotice);
  router.delete('/api/shop/deleteNotice', jwt, controller.shop.deleteNotice);
  router.get('/api/administrators/getAdministrators', jwt, controller.administrators.getAdministrators);
  router.post('/api/administrators/add', jwt, controller.administrators.add);
  router.post('/api/administrators/edit', jwt, controller.administrators.edit);
  router.post('/api/administrators/changePassword', jwt, controller.administrators.changePassword);

};
